trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    displayName: install node
    inputs:
      versionSpec: 12.x

  - task: Npm@1
    displayName: npm install
    inputs:
      command: install

  - task: Npm@1
    displayName: formatting
    inputs:
      command: custom
      customCommand: run format
    condition: succeededOrFailed()

  - task: Npm@1
    displayName: linting
    inputs:
      command: custom
      customCommand: run lint -- --format vso
    condition: succeededOrFailed()

  - task: Npm@1
    displayName: npm build
    inputs:
      command: custom
      customCommand: run build -- auth0-angular --prod

  - task: Npm@1
    displayName: npm publish
    inputs:
      command: publish
      workingDir: dist/auth0-angular
      publishRegistry: useFeed
      publishFeed: 36641032-ec0e-44f3-b65d-00055870227b
