trigger:
  - master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build
    displayName: test and build package
    jobs:
      - job: build
        steps:
          - task: NodeTool@0
            displayName: install node
            inputs:
              versionSpec: 18.x

          - task: Npm@1
            displayName: npm install
            inputs:
              command: ci

          - task: Npm@1
            displayName: formatting
            inputs:
              command: custom
              customCommand: run format
            condition: succeededOrFailed()

          - task: Npm@1
            displayName: linting
            inputs:
              command: custom
              customCommand: run lint -- --format visualstudio
            condition: succeededOrFailed()

          - task: Npm@1
            displayName: test
            inputs:
              command: custom
              customCommand: run test -- --ci --reporters=jest-junit --reporters=default --coverage --coverageReporters=cobertura
            condition: succeededOrFailed()

          - task: PublishTestResults@2
            displayName: publish test results
            inputs:
              testResultsFiles: junit.xml
              testRunTitle: 'Unit Tests'
              mergeTestResults: true
              failTaskOnFailedTests: true
            condition: succeededOrFailed()

          - task: PublishCodeCoverageResults@2
            displayName: publish test coverage
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: coverage/cobertura-coverage.xml
              failIfCoverageEmpty: true
            condition: succeededOrFailed()

          - task: Npm@1
            displayName: npm build auth0
            inputs:
              command: custom
              customCommand: run build -- auth0-angular -c production

          - publish: $(System.DefaultWorkingDirectory)/dist/auth0-angular
            displayName: publish auth0-angular
            artifact: auth0-angular

          - task: Npm@1
            displayName: npm build b2c
            inputs:
              command: custom
              customCommand: run build -- b2c-angular -c production

          - publish: $(System.DefaultWorkingDirectory)/dist/b2c-angular
            displayName: publish b2c-angular
            artifact: b2c-angular

  - stage: publish_auth0
    dependsOn: build
    displayName: publish auth0-angular package to npm
    jobs:
      - deployment: publish
        environment: thecla-npm
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  displayName: download auth0-angular dist
                  artifact: auth0-angular

                - task: Npm@1
                  displayName: npm publish
                  inputs:
                    command: custom
                    customCommand: publish --access public
                    workingDir: $(Pipeline.Workspace)/auth0-angular
                    customEndpoint: npmjs

  - stage: publish_b2c
    dependsOn: build
    displayName: publish b2c-angular package to npm
    jobs:
      - deployment: publish
        environment: thecla-npm
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  displayName: download b2c-angular dist
                  artifact: b2c-angular

                - task: Npm@1
                  displayName: npm publish
                  inputs:
                    command: custom
                    customCommand: publish --access public
                    workingDir: $(Pipeline.Workspace)/b2c-angular
                    customEndpoint: npmjs
